### ISSUE TITLE
Comment-foutje

### ISSUE THREAD

**Issue by spellegrom** [geertw/rdt-serviceinfo#11]
Kleinigheidje in de commenting in serviceinfo/iff.py, lijn 264.

    def get_transport_mode(self, transport_mode):
        """
        Get a transport mode description from the IFF database.
        Args:
            transport_mode (string): Transport mode code (e.g. 'IC')
        Returns:
            string: Transport mode description (e.g. 'Intercity'),
            or None when the station code is not found
        """

"or None when the STATION code is not found" in de functie voor transportmode codes.

Edit: lijn 287, zelfde verhaal met de company codes :)

**Comment by geertw** [comment]
Thanks! Zal er zsm even naar kijken :-)

**Comment by spellegrom** [comment]
Np, ben zelf niet zo handig met Github, dacht doe het maar even zo.
